apiVersion: v1
kind: Service
metadata:
    name: link-enem-aula-backend
    namespace: link-enem-back
spec:
    selector:
        app: link-enem-aula-backend
    ports:
        - port: 80
    type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: link-enem-aula-backend
    namespace: link-enem-back
spec:
    selector:
        matchLabels:
            app: link-enem-aula-backend
    replicas: 1
    template:
        metadata:
            labels:
                app: link-enem-aula-backend
        spec:
            containers:
                - image: IMAGE_NAME
                  imagePullPolicy: Always
                  name: link-enem-aula-backend

                  ports:
                      - containerPort: 80
            restartPolicy: Always
