FROM node:12.13-alpine As development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i -g @nestjs/cli

RUN npm install

COPY . .

RUN npm run build

FROM node:12.13-alpine as production

ARG DB_CONNECTION
ENV DB_CONNECTION=$DB_CONNECTION

ARG DB_HOST
ENV DB_HOST=$DB_HOST

ARG DB_PORT
ENV DB_PORT=$DB_PORT

ARG DB_DATABASE
ENV DB_DATABASE=$DB_DATABASE

ARG DB_USERNAME
ENV DB_USERNAME=$DB_USERNAME

ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD

ARG AZURE_STORAGE_NAME
ENV AZURE_STORAGE_NAME=$AZURE_STORAGE_NAME

ARG AZURE_STORAGE_KEY
ENV AZURE_STORAGE_KEY=$AZURE_STORAGE_KEY

ARG AZURE_STORAGE_CONTAINER
ENV AZURE_STORAGE_CONTAINER=$AZURE_STORAGE_CONTAINER

ARG AZURE_STORAGE_URL
ENV AZURE_STORAGE_URL=$AZURE_STORAGE_URL

ARG AZURE_STORAGE_CONNECTION_STRING
ENV AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING

ARG AZURE_STORAGE_SAS_KEY
ENV AZURE_STORAGE_SAS_KEY=$AZURE_STORAGE_SAS_KEY

ARG URL_APPLICATION
ENV URL_APPLICATION=$URL_APPLICATION

ARG MODULO_URL
ENV MODULO_URL=$MODULO_URL

ARG QUESTAO_DB_CONNECTION
ENV QUESTAO_DB_CONNECTION=$QUESTAO_DB_CONNECTION

ARG QUESTAO_DB_HOST
ENV QUESTAO_DB_HOST=$QUESTAO_DB_HOST

ARG QUESTAO_DB_PORT
ENV QUESTAO_DB_PORT=$QUESTAO_DB_PORT

ARG QUESTAO_DB_DATABASE
ENV QUESTAO_DB_DATABASE=$QUESTAO_DB_DATABASE

ARG QUESTAO_DB_USER
ENV QUESTAO_DB_USER=$QUESTAO_DB_USER

ARG QUESTAO_DB_PASSWORD
ENV QUESTAO_DB_PASSWORD=$QUESTAO_DB_PASSWORD

ARG APP_TIMEZONE
ENV APP_TIMEZONE=$APP_TIMEZONE

ARG AUTH_REDIRECT_URL
ENV AUTH_REDIRECT_URL=$AUTH_REDIRECT_URL

ENV DB_DRIVER=pgsql

ENV NODE_ENV=production

ENV APP_PORT=80

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

EXPOSE 80

CMD ["node", "dist/main"]